name: vent_calc
description: "Калькулятор для проверки вентиляции"
publish_to: 'none'
version: 1.0.0+1

# ⬇️ ЭТУ СЕКЦИЮ НУЖНО ДОБАВИТЬ ⬇️
environment:
  sdk: '^3.0.0'  # Минимальная версия Dart SDK

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
